services:

  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: blog_app
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    networks:
      - app-network

  backend:
    image: 882321772634.dkr.ecr.ap-south-1.amazonaws.com/springboot-demo:backend
    container_name: backend-container
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    networks:
      - app-network

  frontend:
    image: 882321772634.dkr.ecr.ap-south-1.amazonaws.com/springboot-demo:frontend
    container_name: frontend-container
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx-container
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge