version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: blog_app
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    image: 882321772634.dkr.ecr.ap-south-1.amazonaws.com/springboot-demo:backend
    container_name: backend-container
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/blog_app
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8080"
    networks:
      - app-network

  frontend:
    image: 882321772634.dkr.ecr.ap-south-1.amazonaws.com/springboot-demo:frontend
    container_name: frontend-container
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx-container
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge